In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import SparsePCA
import matplotlib.pyplot as plt

In [3]:
data = pd.read_csv ("cars_reduced.csv" , header = None)

In [4]:
data.rename (columns = {0 : "Retail Price" , 1 : "Dealer Price" , 2 : "Wheel base" , 3 : "Length"} ,  inplace = True )

In [5]:
data


Retail Price  Dealer Price  Wheel base  Length
0           43755         39014         115     197
1           46100         41100         115     197
2           36945         33337         106     189
3           89765         79978         100     174
4           23820         21761         101     172
..            ...           ...         ...     ...
397         37730         35542         110     190
398         45210         42573         110     190
399         26135         24641         101     180
400         35145         33112         109     186
401         41250         38851         113     189

[402 rows x 4 columns]

In [6]:
pca_raw = SparsePCA (n_components = 2 , alpha = 5)
pca_raw.fit (data)
pca_raw_components = pca_raw.components_
print (f"Components found using sparse PCA : \n {pca_raw_components} \n ")

Components found using sparse PCA : 
 [[ 7.40925594e-01  6.71587114e-01  4.70385250e-05  9.80024955e-05]
 [-6.40917299e-01  7.67608812e-01  0.00000000e+00 -1.31419263e-03]] 
 


In [7]:
x = data.values

In [28]:
scaler = StandardScaler ()
x_scaled =scaler.fit_transform (x)
print (f"Scaled Data for sparse PCA : \n {x_scaled} \n ")

Scaled Data for sparse PCA : 
 [[ 0.52805557  0.47316971  1.07410878  0.89298847]
 [ 0.64677084  0.58950953  1.07410878  0.89298847]
 [ 0.18330036  0.1565536  -0.17948011  0.29130171]
 ...
 [-0.36395424 -0.32843735 -0.87591838 -0.3855959 ]
 [ 0.09217563  0.14400496  0.23838285  0.06566917]
 [ 0.40124033  0.46407891  0.79553347  0.29130171]] 
 


In [9]:
pca_scaled = SparsePCA (n_components = 2 , alpha = 5)
pca_scaled.fit (x_scaled)

SparsePCA(alpha=5, n_components=2)

In [10]:
pca_scaled_components = pca_scaled.components_
print (pca_scaled_components)

[[0.70710678 0.70710678 0.         0.        ]
 [0.         0.         0.70711058 0.70710298]]


There is a significant difference between The raw based SparsedPCA and Scaled SparsePCA. We can see that the scaled SparsePCA can capture the true relationship between :  (1. retail and dealer price) and (2.wheel base and length). This can strongly support our latent variable model as we have two factors : Price and Length. This gives us a chance to find these two invisible factors and patterns we are looking for. Finally we can conclude that each one of these factors can have influence on our dataset and our results.   